name: CICD

on:
  push:
    branches: ["master"]

env:
  REGISTRY: roxsross12
  IMAGE_NAME: ${{ github.event.repository.name }}
  VERSION: 1.0.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and Tag Images
        run: |
          for service in vote result worker; do
            docker build -t $REGISTRY/$IMAGE_NAME:$service-$VERSION ./$service
          done

      - name: List Images
        run: docker images | grep $REGISTRY/$IMAGE_NAME
